name: Publish Backend Image

on:
  release:
    types: 
      - published
  workflow_dispatch:

env:
  DOCKER_REPO: lofowebteam/tpc_portal_backend

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Version tag if it is release action
        id: meta
        run: |
          if [ ${{ github.action }} == 'published' ]; then
            echo "A release is publised"
            echo "::set-output name=tags::${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}"
          else
            echo "Not a release"
            echo "::set-output name=tags::"
          fi
        shell: bash
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.sha }},${{ env.DOCKER_REPO }}:latest,{{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache,mode=max


  bump_tag:
    name: Bump tag into docker-compose.yml
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout charts
        uses: actions/checkout@v4
        with:
          repository: Web-Team-IITI-Gymkhana/tpc-pipeline-testing
          ref: 'main'
          token: ${{ secrets.TPC_GITHUB_ACTION_ADMIN }}
          path: base_dir
  
      - name: Changing Chart version
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq -i '.services.backend.image = "${{ env.DOCKER_REPO }}:${{ github.sha }}"' base_dir/docker-compose.yml
        
      - name: Commit updated docker compose
        run: |
          cd base_dir
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add docker-compose.yml
          git commit -m "[CI] Bump backend image tag to ${{ github.sha }}"
          git push